# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: 主页
  url: /
  icon:
#- page: 分类
#  url: /categories/
#  icon:
- page: 标签
  url: /tags
  icon:
#- page: 归档
#  url: /archives/
#  icon:
#- page: 前端
#  url: /categories/前端/
#  icon:
#- page: 后端
#  url: /categories/后端/
#  icon:
#- page: 工具
#  url: /categories/tools/
#  icon:
- page: 时间轴
  url: /archives/
  icon:

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml


# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## 网站公告设置
notification: |-
            <p>个人日常笔记
            <br/>
            CSDN博客：<a href="http://blog.csdn.net/eacter" title="wekri" target="_blank">wekri</a>
            </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/wekri
 - name: 邮箱
   icon: envelope-o
   href: mailto:wekri@qq.com
 - name: 联系QQ
   icon: qq
   href: http://wpa.qq.com/msgrd?v=3&uin=519299972&site=qq&menu=yes
 - name: 微博
   icon: weibo
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 友链设置
links:
  - CSDN博客: http://blog.csdn.net/eacter
  - 码云: https://gitee.com/wekri


# 主题自定义个性化配置

## 网站宣传语
branding:

## 设置banner背景图片
banner:
    img: http://7xpw2b.com1.z0.glb.clouddn.com/hexo-sinppet/img/banner2.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

## 文章过期提醒功能
warning:
  days: 900
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="http://wekri.com" target="_blank">wekri</a>


## 主题评论

### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 来必力
livere: 
  enable: false
  livere_uid: MTAyMC8zMzA4Ny85NjQ4

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: true
  appid: cytFbjWUJ
  conf: prod_74a7bae0e350931ba1210284f17d9cf7

## 网站访问统计

### 网盟CNZZ统计
cnzz_analytics: 1271973342

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度文章推送
baidu_push:

#网站主题配置
since: 2017
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1
